# Generated by Django 6.1 on 2026-08-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('electronica', 'Electrónica'), ('ropa', 'Ropa'), ('hogar', 'Hogar')], max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
